# Generated by Django 5.1 on 2024-09-14 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('stock', models.IntegerField()),
                ('delivery_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('fare', models.IntegerField()),
                ('arrival_date', models.DateTimeField()),
                ('Origin', models.TextField(max_length=50)),
                ('Destination', models.TextField(max_length=50)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.farmer')),
            ],
        ),
    ]
