# Generated by Django 5.1 on 2024-09-18 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_farmer_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('PostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.post')),
                ('TransportId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('TruckId', models.AutoField(primary_key=True, serialize=False)),
                ('LicensePlate', models.CharField(max_length=6)),
                ('DriverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.driver')),
            ],
        ),
    ]
