# Generated by Django 5.1 on 2024-09-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_order_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Destination',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='Origin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
