# Generated by Django 5.1 on 2024-09-18 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('DriverId', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('FarmerId', models.AutoField(primary_key=True, serialize=False)),
                ('Country', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Postal_Code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Phone_Number', models.CharField(max_length=20)),
                ('Email_Address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Stock', models.IntegerField()),
                ('DeliveryDate', models.DateField()),
                ('Description', models.CharField(max_length=200)),
                ('Fare', models.IntegerField()),
                ('ArrivalDate', models.DateField()),
                ('LocationOrigin', models.CharField(max_length=50)),
                ('LocationArrival', models.CharField(max_length=50)),
                ('FarmerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ordenes.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('TransportId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ordenes.driver')),
                ('PostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ordenes.post')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('TruckId', models.AutoField(primary_key=True, serialize=False)),
                ('LicensePlate', models.CharField(max_length=6)),
                ('DriverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ordenes.driver')),
            ],
        ),
    ]
